### ISSUE TITLE
 Error: Cannot find module './sourcemap'

### ISSUE THREAD

**Issue by jazzdd86** [sharelatex/web-sharelatex#128]
Hi,
build the system on Arch Linux Rasp Pi. Everything compiled and installed fine. I installed the systemd files and all modules are running.
If I try and access the website on port 3000 the sharelatex-web module fails with:

Exception: Error: Cannot find module './sourcemap'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sharelatex/web/node_modules/translations-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:19:15)
    at Object.<anonymous> (/var/www/sharelatex/web/node_modules/translations-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:347:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sharelatex/web/node_modules/translations-sharelatex/index.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sharelatex/web/app/js/infrastructure/Server.js:48:18)
    at Object.<anonymous> (/var/www/sharelatex/web/app/js/infrastructure/Server.js:175:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sharelatex/web/app.js:18:12)
    at Object.<anonymous> (/var/www/sharelatex/web/app.js:75:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by jazzdd86** [comment]
Hi this is my console output:

```
# npm install
npm WARN package.json connect-redis@1.4.5 No repository field.
npm WARN package.json dateformat@1.0.4-1.2.3 No repository field.
-
> dtrace-provider@0.2.4 install /var/www/sharelatex/web/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

/usr/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: Zeile 2:   558 Getötet                node "`dirname "$0"`/../../node_modules/node-gyp/bin/node-gyp.js" "$@"
npm ERR! Linux 3.12.35-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! dtrace-provider@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the dtrace-provider@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sharelatex/web/npm-debug.log
```

**Comment by jpallen** [comment]
This might be a problem with compiling things on the RPi or Arch. Can you make sure you have node-gyp installed:

```
sudo npm install -g node-gyp
```

**Comment by jazzdd86** [comment]
Hi,
I tried that, still keeps failing with same error messages.

2015-01-05 12:20 GMT+01:00 James Allen <notifications@github.com>:

**Comment by henryoswald** [comment]
you are probably best using the docker image we provide now rather than compiling on raspberry pi.
