### ISSUE TITLE
Crash with ENOENT error

### ISSUE THREAD

**Issue by oxan** [sharelatex/web-sharelatex#174]
Our ShareLaTeX installation crashed tonight (the web process exited) with the following error:

```
{"name":"web-sharelatex","hostname":"knuth","pid":14888,"level":30,"req":{"url":"/project","method":"GET","referrer":"https://latex.arago.utwente.nl/login","remote-addr":"2001:610:1908:8000:a976:5345:be2d:d799","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0"},"res":{"statusCode":200},"response-time":15,"msg":"http request","time":"2015-04-28T21:44:02.889Z","v":0}
{"name":"web-sharelatex","hostname":"knuth","pid":14888,"level":30,"owner_id":"55097673d6e11d3c2937384b","projectName":"cv_10","msg":"creating blank project","time":"2015-04-28T21:44:19.439Z","v":0}
{"name":"web-sharelatex","hostname":"knuth","pid":14888,"level":30,"query":{"_id":"55097673d6e11d3c2937384b"},"query_type":"query","collection":"sharelatex.users","response-time":1,"msg":"mongo request","time":"2015-04-28T21:44:19.443Z","v":0}
{"name":"web-sharelatex","hostname":"knuth","pid":14888,"level":30,"req":{"url":"/stylesheets/loading.gif","method":"GET","referrer":"https://latex.arago.utwente.nl/stylesheets/style.css?fingerprint=cadeda1f057e42984029c3c1212e7f93","remote-addr":"2001:610:1908:8000:a976:5345:be2d:d799","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0"},"res":{"statusCode":404},"response-time":1,"msg":"http request","time":"2015-04-28T21:44:19.448Z","v":0}
{"name":"web-sharelatex","hostname":"knuth","pid":14888,"level":30,"query_type":"insert","collection":"sharelatex.projects","response-time":3,"msg":"mongo request","time":"2015-04-28T21:44:19.448Z","v":0}
{"name":"web-sharelatex","hostname":"knuth","pid":14888,"level":30,"source":"/tmp/sharelatex/uploads/cc8fb42c6afc19615c3c99a8e264e55e","destination":"/tmp/sharelatex/uploads/cc8fb42c6afc19615c3c99a8e264e55e-1430257459449","msg":"unzipping file","time":"2015-04-28T21:44:19.449Z","v":0}
Exception: Error: spawn ENOENT
  at errnoException (child_process.js:1000:11)
  at Process.ChildProcess._handle.onexit (child_process.js:791:34)
```

Not sure what causes this... We're running ShareLaTeX v0.1.2.

**Comment by oxan** [comment]
We've now updated to v0.1.4, I'll see whether we can reproduce it.

**Comment by henryoswald** [comment]
Going to close as its old, I am not sure what caused the crash sorry, main thing to ensure it auto comes back
