### ISSUE TITLE
Errors when stopping and starting service.

### ISSUE THREAD

**Issue by sigurdtheone** [sharelatex/web-sharelatex#183]
I seem to be having issues with completely getting rid of the sharelatex process. I get the "Error: listen EADDRINUSE" when starting socket.io, even after having run "killall node".

Seems like there is still something lingering behind preventing sharelatex from properly starting again.

If i run the "grunt run --force" i can access my sharelatex site without problems.

Is there any way to completely get rid of the process and start it again without having to worry about that exact error, possibly a graceful shutdown?

I am currently implementing a backup solution and i would like to make sure that sharelatex is down for this since the backup documentation states that this is a necessity.(https://github.com/sharelatex/sharelatex/wiki/Backup-of-Data)

```
$ killall node
root@sharelatex01.mydomain:/srv/web/sharelatex/http/sharelatex
$ grunt run
Running "concurrent:all" (concurrent) task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task

Running "execute:document-updater" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/document-updater/app.js

Running "execute:real-time" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/real-time/app.js

Running "execute:filestore" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/filestore/app.js


Running "execute:docstore" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/docstore/app.js
Running "execute:tags" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/tags/app.js

Running "execute:track-changes" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/track-changes/app.js


Running "execute:clsi" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/clsi/app.js

Running "execute:web" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/web/app.js
Running "execute:chat" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/chat/app.js

Running "execute:spelling" (execute) task
-> executing /srv/web/sharelatex/http/sharelatex/spelling/app.js
[2015-05-21T06:42:44.268Z]  INFO: filestore/13195 on sharelatex01: Loading backend (backend=fs)
info: socket.io started

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
Warning: -> error 8 /srv/web/sharelatex/http/sharelatex/tags/app.js (9020ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.

        Aborted due to warnings.

```

**Comment by sigurdtheone** [comment]
I have solved some of the above by using Upstart under ubuntu, eg. starting and stopping the services one by one with "stop sharelatex-web" and so on.

However - as for the backup solution, is it really necessary to stop the services completely if you are simply doing a routine backup with something like rsync and mongodump?
