### ISSUE TITLE
MongoError: driver is incompatible with this server version

### ISSUE THREAD

**Issue by Xarin** [sharelatex/web-sharelatex#323]
Using updated docker image on a RHEL 7 host running mongodb 3.2.9. This happens when trying to create a new project. Web page hangs at creating.

`{"name":"web-sharelatex","hostname":"893e42f3ffb7","pid":71,"level":30,"query_type":"insert","collection":"sharelatex.p
rojects","response-time":1,"msg":"mongo request","time":"2016-09-27T13:44:46.831Z","v":0}
{"name":"csc_test","hostname":"893e42f3ffb7","pid":71,"level":50,"err":{"message":"driver is incompatible with this ser
ver version","name":"MongoError","stack":"MongoError: driver is incompatible with this server version\n  at Object.toEr
ror (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:110:11)\n  at __executeIns
ertCommand (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1829:27)\n  at Db._exe
cuteInsertCommand (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1930:5)\n  at D
b.base.(anonymous function) [as _executeInsertCommand] (/var/www/sharelatex/web/node_modules/metrics-sharelatex/mongodb
.coffee:30:13)\n  at insertAll (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collecti
on/core.js:205:13)\n  at Collection.insert (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mong
odb/collection/core.js:35:3)\n  at NativeCollection.(anonymous function) [as insert] (/var/www/sharelatex/web/node_modu
les/mongoose/lib/drivers/node-mongodb-native/collection.js:129:28)\n  at model.save (/var/www/sharelatex/web/node_modul
es/mongoose/lib/model.js:190:21)\n  at model._done (/var/www/sharelatex/web/node_modules/mongoose/node_modules/hooks/ho
oks.js:59:24)\n  at _next (/var/www/sharelatex/web/node_modules/mongoose/node_modules/hooks/hooks.js:52:28)\n  at fnWra
pper (/var/www/sharelatex/web/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)\n  at complete (/var/www/sharela
tex/web/node_modules/mongoose/lib/document.js:974:5)\n  at /var/www/sharelatex/web/node_modules/mongoose/lib/document.j
s:965:20\n  at /var/www/sharelatex/web/node_modules/mongoose/lib/schema/documentarray.js:100:22\n  at complete (/var/ww
w/sharelatex/web/node_modules/mongoose/lib/document.js:974:5)\n  at /var/www/sharelatex/web/node_modules/mongoose/lib/d
ocument.js:965:20\n  at /var/www/sharelatex/web/node_modules/mongoose/lib/schema/documentarray.js:79:24\n  at DocumentA
rray.SchemaType.doValidate (/var/www/sharelatex/web/node_modules/mongoose/lib/schematype.js:603:22)\n  at DocumentArray
.doValidate (/var/www/sharelatex/web/node_modules/mongoose/lib/schema/documentarray.js:73:35)\n  at /var/www/sharelatex
/web/node_modules/mongoose/lib/document.js:956:9\n  at process._tickDomainCallback (node.js:492:13)\n"},"user":{"id":"5
6af9e168d69986e025ab28c","email":"email@email.com"},"templateType":"example","msg":"error creating project","time
":"2016-09-27T13:44:46.907Z","v":0}
`

Any help would be appreciated.
Thanks.

**Comment by Xarin** [comment]
Fixed using solution here: https://github.com/sharelatex/sharelatex-docker-image/issues/7
