### ISSUE TITLE
Registering new users throws error

### ISSUE THREAD

**Issue by ti-s** [sharelatex/web-sharelatex#392]
When a new user clicks on his activation link and enters a password, he sees the message:

> Your activation token has expired, you will need to get another one sent to you.

 However, the user is successfully registered and can log in with his entered password. 

The log contains the following lines

```
/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Object #<Object> has no method 'doLogin'
  at /var/www/sharelatex/web/app/js/Features/PasswordReset/PasswordResetController.js:91:49
  at Cursor.nextObject (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:773:5)
  at commandHandler (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:741:14)
  at /var/www/sharelatex/web/node_modules/metrics-sharelatex/mongodb.coffee:39:5
  at /var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1903:9
  at Server.Base._callHandler (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
  at /var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
  at [object Object].MongoReply.parseBody (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
  at [object Object].emit (events.js:95:17)
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
  at [object Object].emit (events.js:98:17)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:765:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```
It seems, the method `AuthenticationController.doLogin` was removed in commit 32d8a60731b219ba3de4bf848e343d293f13ab16 but is still called in `PasswordResetController.coffee` on master.

**Comment by JanoschDeurer** [comment]
I have the same issue and reported it for the docker image:
[https://github.com/sharelatex/sharelatex-docker-image/issues/63](url)

**Comment by jpallen** [comment]
This sounds like a mismatch in parts of the code that should now all be up to date. Will close for now, but please reopen if you're still having trouble with the latest docker image/branches
