### ISSUE TITLE
real-time: could not look up session by key: sharelatex.sid

### ISSUE THREAD

**Issue by punkt2** [sharelatex/web-sharelatex#590]
Hello,
I use the sharelatex docker image sharelatex/sharelatex:v0.6.3

I get this error messages in in the real-time log. How does this error affect the functionality of sharelatex? Why does this error happen?

cat /var/log/sharelatex/real-time.log 
{"name":"real-time-sharelatex","hostname":"2b230c1002b5","pid":11075,"level":50,"err":{"message":"could not look up session by key: sharelatex.sid","name":"Error","stack":"Error: could not look up session by key: sharelatex.sid\n  at resolve (/var/www/sharelatex/real-time/node_modules/session.socket.io/session.socket.io.js:41:39)\n  at /var/www/sharelatex/real-time/node_modules/session.socket.io/session.socket.io.js:19:19\n  at /var/www/sharelatex/real-time/node_modules/express-session/session/store.js:71:23\n  at /var/www/sharelatex/real-time/node_modules/connect-redis/lib/connect-redis.js:158:25\n  at try_callback (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/redis/index.js:592:9)\n  at RedisClient.return_reply (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/redis/index.js:685:13)\n  at ReplyParser.<anonymous> (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/redis/index.js:321:14)\n  at ReplyParser.emit (events.js:95:17)\n  at ReplyParser.send_reply (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/redis/lib/parser/javascript.js:300:10)\n  at ReplyParser.execute (/var/www/sharelatex/real-time/node_modules/redis-sharelatex/node_modules/redis/lib/parser/javascript.js:203:22)\n"},"client":true,"session":false,"msg":"invalid session","time":"2017-09-02T01:04:09.804Z","v":0}
warn: client not handshaken client should reconnect

root@2b230c1002b5:/# /usr/bin/node --version
v0.10.48

root@2b230c1002b5:/var/www/sharelatex/real-time# npm list
real-time-sharelatex@0.1.4 /var/www/sharelatex/real-time

├── session.socket.io@0.1.6
├─┬ settings-sharelatex@1.0.0 (git+https://github.com/sharelatex/settings-sharelatex.git#cbc5e41c1dbe6789721a14b3fdae05bf22546559)
│ └── coffee-script@1.6.0
├─┬ sinon@1.5.2
│ └─┬ buster-format@0.5.6
│   └── buster-core@0.6.4
├─┬ socket.io@0.9.16
│ ├── base64id@0.1.0
│ ├── policyfile@0.0.4
│ ├── redis@0.7.3
│ └─┬ socket.io-client@0.9.16

root@c9b8c66b05fb:/# redis-server --version
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9

root@2b230c1002b5:/var/www/sharelatex# grunt check:redis
Running "check:redis" task
Checking can connect to redis
node_redis: Warning: Redis server does not require a password, but a password was supplied.
OK.
Done, without errors.

root@2b230c1002b5:/var/www/sharelatex/real-time# git log
commit 2525feeb9d412336b05f1225460d1c0a75949904
Merge: e2d4271 4421558
Author: James Allen <james@sharelatex.com>
Date:   Tue May 16 11:14:54 2017 +0100

    Merge pull request #14 from sharelatex/ja-dont-return-blank-clients
    
    Don't return a user if there is no entry

**Comment by punkt2** [comment]
I figured it out. I updated sharelatex from version 0.2.0 to the latest docker container. A user still had the old version open in his browser which sent periodic websocket requests without the session key "sharelatex.sid" in the header.
